[build]
  command = "npm run build"
  publish = "dist/HuellitasConectadas"

[build.environment]
  BACKEND_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

